const mongoose=require('mongoose');

const healthProviderSchema=new mongoose.Schema({
    full_name:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    phone_number:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    profile_img:{
        public_id:{
            type:String,
        },
        url:{
            type:String,
        }
    },
    status:{
        type:String,
        required:true
    },
    day:{
        type:String,
        required:true,
        immutable:true
    },
    month:{
        type:String,
        required:true,
        immutable:true
    },
    year:{
        type:String,
        required:true,
        immutable:true
    },
    created_at:{
        type:Date,
        default:()=>Date.now(),
        required:true,
        immutable:true
    },
    updatedAt:{
        type:Date,
        default:()=>Date.now(),
        required:true,
    } 
})

//---------------------------------------------------
module.exports=mongoose.model('healthproviders',healthProviderSchema);