const mongoose=require('mongoose');

const resourceSchema=new mongoose.Schema({
    provider_id:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'healthproviders',
        required:true
    },
    title:{
        type:String,
        required:true
    },
    description:{
        type:String,
        required:true
    },
    content:{
        type:String,
        required:true
    },
    img:{
        public_id:{
            type:String,
            required:true
        },
        url:{
            type:String,
            required:true
        }
    },
    status:{
        type:String,
        required:true
    },
    day:{
        type:String,
        required:true,
        immutable:true
    },
    month:{
        type:String,
        required:true,
        immutable:true
    },
    year:{
        type:String,
        required:true,
        immutable:true
    },
    created_at:{
        type:Date,
        default:()=>Date.now(),
        required:true,
        immutable:true
    },
    updatedAt:{
        type:Date,
        default:()=>Date.now(),
        required:true,
    } 
})

//---------------------------------------------------
module.exports=mongoose.model('resources',resourceSchema);